### ISSUE TITLE
Test 2-3 relayers intances running in pararell

### ISSUE THREAD

**Issue by koonopek** [redstone-finance/redstone-oracles-monorepo#503]
In the first step sharing the same private key

**Comment by koonopek** [comment]
1 .So the test with Nonce was completed successfully only 1 of three nodes send transaction
2. However one node send two transactions in  row (need investigation)

Contract: https://goerli.arbiscan.io/address/0xcEbA69D8C1ab497E8c55b19d33d5dc9427Ea065A

**Comment by koonopek** [comment]
Okey scheduler overall is behaving weird:
```bash
[31/Mar/2023:23:07:45] All conditions are not fulfilled: ["Not enough time has passed to update prices"]
[31/Mar/2023:23:07:46] All conditions are not fulfilled: ["Not enough time has passed to update prices"]
[31/Mar/2023:23:07:49] All conditions are not fulfilled: ["Not enough time has passed to update prices"]
[31/Mar/2023:23:08:45] All conditions are not fulfilled: ["Not enough time has passed to update prices"]
[31/Mar/2023:23:08:46] All conditions are not fulfilled: ["Not enough time has passed to update prices"]
```
Look at the timestamps, this actions should take place in 6s intervals ...

**Comment by koonopek** [comment]
I would suggest using `setInterval` instead of this toadScheduler thing - it may be causing issues.
And it is using setInterval underneath anyway

**Comment by koonopek** [comment]
For 45 minutes:
```
[1/Apr/2023:09:40:21] at processTicksAndRejections (node:internal/process/task_queues:96:5)
[1/Apr/2023:09:41:10] Error: processing response error (body="{\"jsonrpc\":\"2.0\",\"id\":48,\"error\":{\"code\":-32000,\"message\":\"intrinsic gas too low\"}}\n", error={"code":-32000}, requestBody="{\"method\":\"eth_sendRawTransaction\",\"params\":[\"0x02f9016b83066eed188459682f00846553f1008398968094ceba69d8c1ab497e8c55b19d33d5dc9427ea065a80b8fcff9e4ee20000000000000000000000000000000000000000000000000000000000000011000000000000000000000000000000000000000000000000000001873c30218056535400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000005f59d5801873c3021800000002000000177b2f603951397fa6d279ea49ac72d18395785f79c0647474dd6dea734b995597192956015918e8d4638b194fc94e8fe7466b1584f1328b53137fec047c429e31c0001302e302e313923646174612d7061636b616765732d7772617070657200001c000002ed57011e0000c080a0ab87f5c3a6b28dba6e20a770a5ed2d65917dbea516e28eeacbc1930b74760120a0564071a13808e0f40e7c745cc62dbcb2ac4ff85105a1db9c6129668aed5485e6\"],\"id\":48,\"jsonrpc\":\"2.0\"}", requestMethod="POST", url="https://goerli-rollup.arbitrum.io/rpc", code=SERVER_ERROR, version=web/5.7.1)
[1/Apr/2023:09:41:10] at Logger.makeError (/app/node_modules/@ethersproject/logger/lib/index.js:238:21)
[1/Apr/2023:09:41:10] at Logger.throwError (/app/node_modules/@ethersproject/logger/lib/index.js:247:20)
[1/Apr/2023:09:41:10] at /app/node_modules/@ethersproject/web/lib/index.js:313:32
[1/Apr/2023:09:41:10] at step (/app/node_modules/@ethersproject/web/lib/index.js:33:23)
[1/Apr/2023:09:41:10] at Object.next (/app/node_modules/@ethersproject/web/lib/index.js:14:53)
[1/Apr/2023:09:41:10] at fulfilled (/app/node_modules/@ethersproject/web/lib/index.js:5:58)
[1/Apr/2023:09:41:10] at runMicrotasks (<anonymous>)
```
On all nodes, thus probably problems with RPC endpoint (fallback mechanism needed)

**Comment by cehali** [comment]
Hey, you have an interval of 60000 milliseconds and it seems that the scheduler is working fine. You have each of your 3 containers working in 1-minute intervals.

**Comment by koonopek** [comment]
@cehali For me it seems like 3 second interval
[31/Mar/2023:23:07:46] All conditions are not fulfilled: ["Not enough time has passed to update prices"]
[31/Mar/2023:23:07:49] All conditions are not fulfilled: ["Not enough time has passed to update prices"]

**Comment by koonopek** [comment]
On balance, after 66 hours:
```bash
┌─────────────┬───────────────────┐
│   (index)   │      Values       │
├─────────────┼───────────────────┤
│ workingTime │ 61.34111111111111 │
│   failed    │         1         │
│ duplicated  │        11         │
│   gasUsed   │   0.0009346272    │
│ gasUsedUsd  │  1.667898316032   │
└─────────────┴───────────────────┘

[on-chain-relayer-1.csv](https://github.com/redstone-finance/redstone-oracles-monorepo/files/11136232/on-chain-relayer-1.csv)


```

**Comment by koonopek** [comment]
![Image](https://user-images.githubusercontent.com/24699136/229455593-b834fbb0-cb82-4213-8217-414bcc90d63d.png)

**Comment by koonopek** [comment]
Till now 3 VMs were running 3 containers via common container service.
As @cehali  suggested I have separated them into 3 container services with one VM and container each.
This required redeployment we will see if double logging will disappear (maybe it was cause by lightsail logs not working properly)

**Comment by koonopek** [comment]
Raport from last 22 hours:
┌─────────────────┬────────────────────┐
│     (index)     │       Values       │
├─────────────────┼────────────────────┤
│ workingTime [h] │      '22.26'       │
│     failed      │         1          │
│   duplicated    │         1          │
│     gasUsed     │  110877674.65077   │
│   gasUsedUsd    │ 201.29620077497995 │
│  gasUsedPerTx   │ 4820768.463076956  │
└─────────────────┴────────────────────┘

**Comment by koonopek** [comment]
Next 24 hours:
```bash
┌─────────────────┬────────────────────┐
│     (index)     │       Values       │
├─────────────────┼────────────────────┤
│ workingTime [h] │      '26.20'       │
│     failed      │         2          │
│   duplicated    │         0          │
│     gasUsed     │   83807438.82108   │
│   gasUsedUsd    │ 160.08561733847418 │
│  gasUsedPerTx   │ 3223363.0315799997 │
└─────────────────┴────────────────────┘
```

**Comment by koonopek** [comment]
Summary:
```bash
┌─────────────────┬───────────────────┐
│     (index)     │      Values       │
├─────────────────┼───────────────────┤
│ workingTime [h] │     '112.76'      │
│     failed      │         4         │
│   duplicated    │        12         │
│     gasUsed     │  354539980.34866  │
│   gasUsedUsd    │ 677.2919060592591 │
│  gasUsedPerTx   │ 2859193.389908548 │
└─────────────────┴───────────────────┘
```
